name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs once a day
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: aribashaikh02
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#dc2626&color_dots=#1a0000,#7f1d1d,#b91c1c,#dc2626,#ef4444

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
